apiVersion: v1
kind: Service
metadata:
  name: categorie-service-nodeport
  labels:
      app: categorie-service
spec:
  selector:
    app: categorie-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: NodePort
    