apiVersion: v1
kind: Pod
metadata:
  name: categorie-service
  labels:
    app: categorie-service
spec:
  containers:
    - name: categorie-service
      image: achrafrabbouche/categorie-service:latest
      ports:
        - containerPort: 80
          name: demo-http
          