apiVersion: v1
kind: Service
metadata:
  name: anime-service-nodeport
  labels:
      app: anime-service
spec:
  selector:
    app: anime-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort