version: '3'

services:
  api-gateway:
    image: achrafrabbouche/api-gateway
    ports:
      - "5002:5002"

  anime-service:
    image: achrafrabbouche/anime-service
    ports:
      - "5000:5000"
    depends_on:
      - api-gateway

  categorie-service:
    image: achrafrabbouche/categorie-service
    ports:
      - "5001:5001"
    depends_on:
      - api-gateway

